version: '3.1'

services:
  webapi:
    build: ./n2b-backend
    networks:
      - m2b-challenge-net
    expose:
      - 5000
    command: gunicorn wsgi:webapi -k gevent --worker-connections 1000 -b 0.0.0.0:5000

  frontend: 
    build: ./n2b-frontend
    networks:
      - m2b-challenge-net

  nginx:
    build: ./nginx
    networks:
      - m2b-challenge-net
    ports:
      - 80:8000
      - 8080:8080
    depends_on:
      - frontend
      - webapi

networks:
  m2b-challenge-net:
    driver: bridge
